# In docker/app/docker-compose.yaml
services:
  backend:
    build: 
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    expose:
      - "8000"
    volumes:
      - ../../backend:/app
      - ../../backend/test_certificate/tmp/lxd.crt:/app/certs/lxd.crt:ro
      - ../../backend/test_certificate/tmp/lxd.key:/app/certs/lxd.key:ro
    environment:
      - DB_HOST=postgresql
      - LXD_CERT_PATH=/app/certs/lxd.crt
      - LXD_KEY_PATH=/app/certs/lxd.key
      - APP_ENV=${APP_ENV:-dev}
      - DOCKER=true
    networks:
      - cloudboi-network
  frontend:
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    expose:
      - "3000"
    volumes:
      - ../../frontend:/app
      - cloudboi_fe-node_modules:/app/node_modules
    environment:
      - VITE_API_URL=${API_URL}
      - VITE_APP_ENV=${APP_ENV:-dev}
    depends_on:
      - backend
    networks:
      - cloudboi-network
  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ../../docker/app/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - cloudboi-network

volumes:
  cloudboi_fe-node_modules:

networks:
  cloudboi-network:
    external: true