# In docker/app/docker-compose.yaml
services:
  backend:
    build: 
      context: ../../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../../backend:/app
    environment:
      - DB_HOST=postgresql
    networks:
      - cloudboi-network

networks:
  cloudboi-network:
    external: true