services:
  postgresql:
    image: postgres:alpine # Use the latest official PostgreSQL image
    restart: always # Always restart the container if it stops
    environment:
      POSTGRES_USER: ${DATABASE_USER:-cloudboi} # Set the PostgreSQL username
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-cloudboi} # Set a strong password
      POSTGRES_DB: ${DATABASE_NAME:-cloudboidb} # Set the default database name
    ports:
      - "5433:5432" # Map port 5433 on the host to port 5432 in the container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cloudboi-network

  pgadmin:
    image: dpage/pgadmin4:latest # Use the latest official pgAdmin image
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # Set pgAdmin email
      PGADMIN_DEFAULT_PASSWORD: admin # Set pgAdmin password
    ports:
      - "5050:80" # Map port 5050 on the host to port 80 in the container
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgresql # Ensure PostgreSQL starts before pgAdmin
    networks:
      - cloudboi-network

networks:
  cloudboi-network:
    name: cloudboi-network

volumes:
  postgres-data:
  pgadmin-data: